# Generated by Django 4.2.1 on 2023-05-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_week_name_alter_week_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='description',
        ),
    ]
