# Generated by Django 4.2.1 on 2023-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_week_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='days',
            field=models.CharField(choices=[('MN', 'Monday'), ('WED', 'Wednesday'), ('FRI', 'Friday')], max_length=300, null=True),
        ),
    ]
