# Generated by Django 4.2.1 on 2023-05-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_days_alter_week_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
    ]
