# Generated by Django 4.2.1 on 2023-05-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_training_delete_days_delete_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
