# Generated by Django 4.2.1 on 2023-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_training_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='description',
            new_name='description_week',
        ),
        migrations.AddField(
            model_name='training',
            name='train1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='train2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='train3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='train4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='train5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='train6',
            field=models.TextField(null=True),
        ),
    ]
