# Generated by Django 4.2.1 on 2023-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_description_training_description_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True, verbose_name='URL'),
        ),
    ]
